### ISSUE TITLE
Crypto.js error...

### ISSUE THREAD

**Issue by justbill2020** [gtjoseph/mikronode-ng#14]
When running any the example I get this error... this was caused when running `examples/getInterfacesAndRoutes.js` 
any help would be greatly appreciated.. 

```crypto.js:74
  this._handle.update(data, encoding);
               ^

TypeError: Data must be a string or a buffer
    at TypeError (native)
    at Hash.update (crypto.js:74:16)
    at myHash (/home/bmartin/dev/mikronode-ng/mikronode-ng/lib/connection.js:112:39)
    at new Connection (/home/bmartin/dev/mikronode-ng/mikronode-ng/lib/connection.js:114:13)
    at Object.getConnection (/home/bmartin/dev/mikronode-ng/mikronode-ng/lib/index.js:73:9)
    at Object.<anonymous> (/home/bmartin/dev/mikronode-ng/mikronode-ng/examples/getInterfacesAndRoutes.js:10:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

**Comment by justbill2020** [comment]
I'm going to close this... the variable I passed as `data` i had to convert explicitly to string using the `.toString` method...
