### ISSUE TITLE
Trap still exists after closing channel using promises

### ISSUE THREAD

**Issue by craftbyte** [gtjoseph/mikronode-ng#3]
When I am using getCommandPromise, once I trigger a trap on the channel, the trap keeps existing even after the channel closes. This means that even after I close the channel I am getting rejected promises for successfully executed commands and the only way to get the trap out is to reinitiate a conenction. What is the correct way to handle that? Either the trap gets cleared or the commandpromise method has to use a channel with a higher ID.

**Comment by gtjoseph** [comment]
Hmmm.  let me check on this.

**Comment by lukyer** [comment]
I've already fixed this issue in my fork. Try it and we can merge it.
https://github.com/lukyer/mikronode

**Comment by gtjoseph** [comment]
Thanks.  I'll take a look and get it merged this weekend.

**Comment by gtjoseph** [comment]
@lukyer Can you create a pull request for the things you've fixed?  I notice that there are others besides the traps.

**Comment by gtjoseph** [comment]
@lukyer Still around?  Can you create the pull request?

**Comment by lukyer** [comment]
Sorry i am waiting with PR because i am not sure at all what my change could cause to other parts of the library. Now i am having issues with commands like "=count-only=" which are not propagating result from "=ret". It may be caused by my change i have to test it.

I don't want to mess your code with untested special purpose changes.

**Comment by gtjoseph** [comment]
Gotcha.  I'll see if I can grab that one change then.

**Comment by craftbyte** [comment]
@gtjoseph any luck?

**Comment by gtjoseph** [comment]
rats,  I completely forgot.   I'll do this tonight.

**Comment by gtjoseph** [comment]
v1.0.8 pushed and published.  Please test.

**Comment by craftbyte** [comment]
for some reason, I am getting a this socket is closed error now when executing commands. Was it in the 1.0.7 that you changed something?

**Comment by craftbyte** [comment]
here is the part of the code:

``` javascript

app.post('/allowed', (req, res) => {
    console.log(req.body, 'connected:', JSON.stringify(openConn))
    if (connected) {
        openConn.getCommandPromise('/ip/firewall/address-list/add', {
            '=list': "allowed",
            '=address': req.body.address,
            '=comment': req.body.comment || ""
        }).then(function resolved(values) {
            console.log(values)
            res.send(JSON.stringify(values));
        }, function rejected(reason) {
            console.log(reason)
            res.status(400).send(JSON.stringify(reason));
        }
        );
    } else {
        console.log(0)
        res.sendStatus(400)
    }
})
```

and the console log

```
{ address: '1.2.3.4', comment: 'test' } 'connected:' '{"hash":"cdd2145d885d5527f56e4f0f08e53ff4","host":"172.16.0.133","user":"admin","password":"anze","port":8728,"timeout":1800,"status":"Connected","channels":{},"closeOnDone":false,"closeOnTimeout":false,"_events":{},"_eventsCount":0}'
Error: This socket is closed
    at Socket._writeGeneric (net.js:672:19)
    at Socket._write (net.js:724:8)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Socket.Writable.write (_stream_writable.js:220:11)
    at Socket.write (net.js:650:40)
    at /Users/anze/Dropbox/Event - Anže - Beni/Mikrotik/node_modules/mikronode-ng/lib/connection.js:446:20
    at Array.forEach (native)
    at Connection.write [as _write] (/Users/anze/Dropbox/Event - Anže - Beni/Mikrotik/node_modules/mikronode-ng/lib/connection.js:444:8)
    at Channel.write (/Users/anze/Dropbox/Event - Anže - Beni/Mikrotik/node_modules/mikronode-ng/lib/channel.js:295:23)
```

**Comment by gtjoseph** [comment]
That's odd.  I ran the tests on several devices and they were fine.  1.0.7 was just a readme update.  Can you go back to 1.0.6 and see if you still get this error?

**Comment by craftbyte** [comment]
Works on v1.0.6

Console Log:

```
{ address: '1.2.3.4', comment: 'ad' } 'connected:' '{"hash":"4c2cc434b569fb890588482a3e6c4d8c","host":"192.168.1.168","user":"admin","password":"anze","port":8728,"timeout":1800,"status":"Connected","channels":{},"closeOnDone":false,"closeOnTimeout":false,"_events":{"error":[null],"timeout":[null,null]},"_eventsCount":4}'
[ { ret: '*1' } ]
```

**Comment by craftbyte** [comment]
Note that the IP is different because I am running the router in a VM which is on a bridged network interface.

**Comment by gtjoseph** [comment]
Ok, let me test again.

**Comment by craftbyte** [comment]
any results?

**Comment by gtjoseph** [comment]
Ah, sorry.  I'll be working on this today.

**Comment by gtjoseph** [comment]
I just tried with your code snippet (without the express bits) and it worked fine.  Can you test with just this and see what happens?

``` javascript
var MikroNode = require('../lib/index.js');

var connection = new MikroNode.Connection(process.argv[2], process.argv[3], process.argv[4], {
    closeOnDone : true,
    closeOnTimeout : true,
    timeout : 4,
});

var connPromise = connection.getConnectPromise().then(function connected(conn) {
    conn.getCommandPromise('/ip/firewall/address-list/add', {
        '=list' : "allowed",
        '=address' : "192.168.111.111",
        '=comment' : "some comment"
    }).then(function resolved(values) {
        console.log(values);
    }, function rejected(reason) {
        console.log(reason);
    });
});
```

**Comment by craftbyte** [comment]
Before I do that, is it possible that the issue could be that I dont do
close on done?

**Comment by gtjoseph** [comment]
> Before I do that, is it possible that the issue could be that I dont do
> close on done?

It's hard to say because I don't know what context you're making this call in.  Are there other commandPromises or channels open at the time?   Could another callback have closed the connection on you?

**Comment by craftbyte** [comment]
You can check the whole code here: https://gist.github.com/craftbyte/a1bfb6a06dba0f75e63eafff22b37568 (will delete after issue resolved)

**Comment by gtjoseph** [comment]
When I said "It's hard to say because I don't know what context you're making." I didn't mean I'd debug your code. :)

However, you close the connection when `req.body.connected == false && connected` so is it possible you're not getting req.body.connected or that you have your logic reversed?   I ask because the word req.body.**connected** implies that the connection is already open.   Do _any_ of the uris work?  If you start the server and run /connect then /data does it wiork?
