### ISSUE TITLE
TypeError: Cannot read property 'ret' of undefined

### ISSUE THREAD

**Issue by fpena06** [gtjoseph/mikronode-ng#8]
Hello I have the following error when I try running any of the code examples. I have used the PHP for mikrotik and confirmed API connections are being allowed. Node v6.1.0

```
/node_modules/mikronode-ng/lib/connection.js:585
                challenge.write(parsed[0].ret, _(_this).password.length + 1, 'hex');
                                         ^

TypeError: Cannot read property 'ret' of undefined
    at Channel.loginDone (/node_modules/mikronode-ng/lib/connection.js:585:30)
    at emitTwo (events.js:106:13)
    at Channel.emit (events.js:191:7)
    at Channel._done (/node_modules/mikronode-ng/lib/channel.js:321:9)
    at Connection.sentence (/node_modules/mikronode-ng/lib/connection.js:299:37)
    at Connection._read (/node_modules/mikronode-ng/lib/connection.js:409:11)
    at Socket.<anonymous> (/node_modules/mikronode-ng/lib/connection.js:491:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
```

**Comment by gtjoseph** [comment]
There was an authentication issue a while ago.  What version of mikronode-ng are you running?  It needs to be 1.0 5 or greater to use nodejs 6+.  Also can you try nodejs 6.2.2?

Forgot to ask...  what version of RouterOS are you running against?

**Comment by fpena06** [comment]
Im running Router os 6.5, mikronode-ng latest (mikronode-ng-3.9.5), and updated to node 6.2.2 didn't fix anything.

**Comment by gtjoseph** [comment]
Oh boy, RouterOS 6.5.  I'm going to have to seriously downrev a device to test that.

Any chance you could upgrade that to 6.36 just as test?

**Comment by fpena06** [comment]
I'll downgrade in the near future. Is there a version that would work with 6.5?

**Comment by gtjoseph** [comment]
Well, I don't _know_ the issue is related to 6.5, it was just guess.   I might be able to downgrade a device this evening and see.  You might want to try one of the earlier versions of the original mikronode,

**Comment by fpena06** [comment]
I can confirm its working after routerOs upgrade. Thanks mate.
